# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="blood&Fire_TheHeavy.mp3"
Content-Type: audio/mpeg

< ./blood&Fire_TheHeavy.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/62f84114-6ba1-4baf-8448-f958230151eb/transcription
Content-Type: application/json

{
  "prompt": "musica"
}